version: '3.8'

services:
  products:
    build: ./products-api
    container_name: products
    ports:
      - "3001:3001"

  orders:
    build: ./orders-api
    container_name: orders
    ports:
      - "3002:3002"
    depends_on:
      - products
      - redis
      - db

  payments:
    build: ./payments-api
    container_name: payments
    ports:
      - "3003:3003"
    depends_on:
      - orders

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    ports:
      - "3666:3666"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
